name: Run tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Sync dependencies
        run: rye sync

      - name: Set up antlr4
        run: pip install antlr4-tools

      - name: Create parser
        working-directory: project/graph_query_language
        run: antlr4 Language.g4 -Dlanguage=Python3

      - name: Run tests
        run: python scripts/run_tests.py
